version: '3.9'

services:
  pairdrop:
    container_name: pairdrop
    image: lscr.io/linuxserver/pairdrop:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuching
      - RATE_LIMIT=false #optional
      - WS_FALLBACK=false #optional
      - RTC_CONFIG= #optional
      - DEBUG_MODE=false #optional
    ports:
      - 3000:3000
    restart: unless-stopped